# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Rust
      uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    - name: Build DTGaussProcess
      run: wasm-pack build
      working-directory: dtgaussprocess
    - name: Install frontend🔧
      run: npm ci
      working-directory: frontend
    - name: Build frontend
      run: npm run build
      working-directory: frontend
    - name: Deploy frontend 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: frontend/dist
