apiVersion: apps/v1
kind: Deployment
metadata:
  name: amiworking
spec:
  selector:
    matchLabels:
      app: amiworking
  template:
    metadata:
      labels:
        app: amiworking
    spec:
      volumes:
        - name: key-volume
          configMap:
            name: pubsub-key
      containers:
        - name: amiworking
          image: haavardm/amiworking
          imagePullPolicy: Always
          resources:
            limits:
              memory: "10Mi"
              cpu: "5m"
          volumeMounts:
            - name: key-volume
              mountPath: /etc/config
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/config/key.json
          ports:
            - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: amiworking
spec:
  selector:
    app: amiworking
  ports:
    - port: 80
      targetPort: 3030
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amiworking
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    name: amiworking
spec:
  tls:
    - hosts:
        - amiworking.shapingideas.fyi
      secretName: amiworking-tls
  rules:
    - host: amiworking.shapingideas.fyi
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: amiworking
                port:
                  number: 80
